version: "3.8"
services:
  workitemsdb:
    image: postgres:15-alpine
  identity4db:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    image: justin2004/mssql_server_tiny
  portfolio_rabbitmq:
    image: rabbitmq:3.8.14-management
  maildb:
    image: mongo
  settingdb:
    image: mongo
  identityserver.api:
    image: ghcr.io/frtlec/portfolio-identityserver:latest
    build:
      context: .
      dockerfile: IdentityServer/Portfolio.IdentityServer/Dockerfile
  photostock.api:
    image: ghcr.io/frtlec/portfolio-photostock:latest
    build:
      context: .
      dockerfile: Services/PhotoStock/Portfolio.Services.PhotoStock/Dockerfile
  mailsender.api:
    image: ghcr.io/frtlec/portfolio-mailsender:latest
    build:
      context: .
      dockerfile: MailSender/Portfolio.Services.MailSender/Dockerfile
  workitem.api:
    image: ghcr.io/frtlec/portfolio-workitem:latest
    build:
      context: .
      dockerfile: Services/WorkItems/Portfolio.Services.WorkItems.API/Dockerfile
  setting.api:
      image: ghcr.io/frtlec/portfolio-setting:latest
      build:
        context: .
        dockerfile: Services/Setting/Porfolio.Services.Setting.API/Dockerfile
  selinozoglu.webui:
    image: ghcr.io/frtlec/portfolio-selinozoglu-webui:latest
    build:
      context: .
      dockerfile: WebUI/SelinOzoglu/selin.ozoglu/Dockerfile
  gateway.api:
    image: ghcr.io/frtlec/portfolio-gateway:latest
    build:
      context: .
      dockerfile: Gateway/Portfolio.Gateway/Dockerfile
volumes:
  workitemsdb_volume:
  identity4db_volume:
  maildb_volume:
  settingdb_volume:
networks:
  closed_network:
    driver: bridge
