version: "3.8"
services:
  workitemsdb:
    container_name: workitemsdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - workitemsdb_volume:/var/lib/postgresql/data2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zk147olu
      - POSTGRES_DB=workitemsdb
  portfolio_rabbitmq:
    container_name: portfolio_rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  maildb:
    container_name: maildb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - maildb_volume:/data/db
  settingdb:
    container_name: settingdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - settingdb_volume:/data/db
  identity4db:
    container_name: identity4db
    user: root
    restart: always
    ports:
      - "1433:1433"
    expose:
      - 1433
    volumes:
      - identity4db_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=zk147olu
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
    ports:
      - "5104:80"
    restart: on-failure
    volumes:
      - type: bind
        source: /root/opt/app_data/portfolio_photostock_data
        # source: C:\Users\zafer\Desktop\photos
        target: /app/wwwroot/photos
  mailsender.api:
    container_name: mailsender.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=portfolio_rabbitmq
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://maildb:27017
    restart: on-failure
    ports:
      - "5103:80"
    depends_on:
      - maildb
  setting.api:
    container_name: setting.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://settingdb
    restart: on-failure
    ports:
      - "5105:80"
    depends_on:
      - settingdb
  workitem.api:
    container_name: workitem.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=admin; Password=zk147olu; Server=workitemsdb; Port=5432;Database=workitemsdb;Integrated Security=true;Pooling=true"
    ports:
      - "5102:80"
    restart: on-failure
    depends_on:
      - workitemsdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identity4db,1433;Database=Identity4DbDeploy;User=sa;Password=zk147olu"
      - TokenOptions:IssuerUri=http://identityserver.api
    ports:
      - "5101:80"
    depends_on:
      - identity4db
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://identityserver.api
    restart: on-failure
    ports:
      - "5100:80"
  selinozoglu.webui:
    container_name: selinozoglu.webui
    restart: on-failure
    ports:
      - "5110:80"
    depends_on:
      - identityserver.api
      - mailsender.api
      - workitem.api
      - photostock.api
