version: "3.8"
services:
  workitemsdb:
    image: postgres
  identity4db:
    image: mcr.microsoft.com/mssql/server:2019-latest
  portfolio_rabbitmq:
    image: rabbitmq:3.8.14-management
  maildb:
    image: mongo
volumes:
  workitemsdb_volume:
  identity4db_volume:
  maildb_volume: