// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Api.Settings.Infrastructure;

#nullable disable

namespace Portfolio.Api.Settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260816185044_Net10Upgrade")]
    partial class Net10Upgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Api.Settings.Models.DbModels.AboutPage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Businesses")
                        .HasColumnType("jsonb");

                    b.Property<string>("Certifacates")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Educations")
                        .HasColumnType("jsonb");

                    b.Property<string>("PortreFileName")
                        .HasColumnType("text");

                    b.Property<string>("Projects")
                        .HasColumnType("jsonb");

                    b.Property<string>("Slogan")
                        .HasColumnType("text");

                    b.Property<string>("Softwares")
                        .HasColumnType("jsonb");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AboutPages", "settings");
                });

            modelBuilder.Entity("Portfolio.Api.Settings.Models.DbModels.Localization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int>("LocalizationType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Localizations", "settings");
                });
#pragma warning restore 612, 618
        }
    }
}
